In [2]:
import numpy as np

In [3]:
array1d = np.array([1,2,3])

In [4]:
# 1D Array = also known as VECTOR
array1d 

array([1, 2, 3])

In [5]:
type(array1d)

numpy.ndarray

In [6]:
array2d = np.array([[1,2,3],[4,5,6]]) 

In [7]:
# 2D Array = also known as MATRIX
array2d

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
array3d = np.array([[[1,2,3],[4,5,6],[7,8,9]], [[1,2,3],[4,5,6],[7,8,9]]])

In [9]:
array3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [10]:
array3d.shape 

(2, 3, 3)

In [11]:
array2d.shape 

(2, 3)

In [12]:
array1d.shape 

(3,)

In [13]:
a4d = np.array([[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]], [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]],[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]], [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]])

In [14]:
a4d

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],

        [[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],

        [[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [15]:
a4d.shape

(2, 2, 4, 3)

In [16]:
a4d.ndim

4

In [17]:
array3d.ndim

3

In [18]:
array2d.ndim

2

In [19]:
array3d.dtype

dtype('int32')

In [20]:
a4d.dtype

dtype('int32')

In [21]:
array3d.size

18

In [22]:
a4d.size

48

In [23]:
type(array3d)

numpy.ndarray

In [24]:
import pandas as pd

In [25]:
df = pd.DataFrame(array2d)

In [26]:
df

0  1  2
0  1  2  3
1  4  5  6


# Creating Numpy Array

In [27]:
test_array = np.array([1,2,3])

In [28]:
test_array

array([1, 2, 3])

In [29]:
# zeros
# Ones
# Randoms
## Size = dimension of matrix

In [30]:
one = np.ones((2,3))

In [31]:
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
one.dtype

dtype('float64')

In [33]:
zero = np.zeros((2,3))

In [34]:
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
range_array = np.arange(0,12,2)    # (start,stop,stepsize )

In [36]:
range_array 

array([ 0,  2,  4,  6,  8, 10])

In [37]:
random_matrix = np.random.randint(0,10,size=(3,5))# Manual Range    ##(start,stop, size=(3,5))

In [38]:
random_matrix 

array([[8, 8, 6, 9, 5],
       [9, 5, 8, 2, 6],
       [6, 2, 3, 8, 9]])

In [39]:
random_matrix.size

15

In [40]:
random_matrix.shape

(3, 5)

In [41]:
rand_matrix = np.random.rand(3,5) # Auto Range

In [42]:
rand_matrix

array([[0.74007504, 0.1435685 , 0.6792928 , 0.11333203, 0.57058885],
       [0.02939061, 0.51703239, 0.69417441, 0.23372335, 0.4626482 ],
       [0.87602902, 0.05979808, 0.97523802, 0.87081241, 0.71584892]])

In [43]:
rand_matrix.sum()

7.681552635690827

In [44]:
# Seed # To fix the sum
np.random.seed(seed=0)
raand_matrix = np.random.rand(3,5) 

In [45]:
raand_matrix.sum()

9.042960048565472

## Accessing Elements

In [46]:
array3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [47]:
array2d

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
array2d[0]

array([1, 2, 3])

In [49]:
array2d[1]

array([4, 5, 6])

In [50]:
array3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [51]:
array3d[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
array3d[1]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
array3d[:2,:2]

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [54]:
array3d[:2,:1]



array([[[1, 2, 3]],

       [[1, 2, 3]]])

In [55]:
array3d[:2,:1,:2]

array([[[1, 2]],

       [[1, 2]]])

In [56]:
arandom = np.random.randint(10, size = (3,3)) #2 dimensional

In [57]:
arandom

array([[9, 4, 3],
       [0, 3, 5],
       [0, 2, 3]])

In [58]:
a3random = np.random.randint(10, size = (3,3,3)) #3 dimensional

In [59]:
a3random 

array([[[8, 1, 3],
        [3, 3, 7],
        [0, 1, 9]],

       [[9, 0, 4],
        [7, 3, 2],
        [7, 2, 0]],

       [[0, 4, 5],
        [5, 6, 8],
        [4, 1, 4]]])

In [60]:
aarandom = np.random.randint(10, size = (3,4,5))

In [61]:
aarandom

array([[[9, 8, 1, 1, 7],
        [9, 9, 3, 6, 7],
        [2, 0, 3, 5, 9],
        [4, 4, 6, 4, 4]],

       [[3, 4, 4, 8, 4],
        [3, 7, 5, 5, 0],
        [1, 5, 9, 3, 0],
        [5, 0, 1, 2, 4]],

       [[2, 0, 3, 2, 0],
        [7, 5, 9, 0, 2],
        [7, 2, 9, 2, 3],
        [3, 2, 3, 4, 1]]])

In [62]:
arrandom = np.random.randint(10, size = (2,3,4,5))

In [63]:
arrandom

array([[[[2, 9, 1, 4, 6],
         [8, 2, 3, 0, 0],
         [6, 0, 6, 3, 3],
         [8, 8, 8, 2, 3]],

        [[2, 0, 8, 8, 3],
         [8, 2, 8, 4, 3],
         [0, 4, 3, 6, 9],
         [8, 0, 8, 5, 9]],

        [[0, 9, 6, 5, 3],
         [1, 8, 0, 4, 9],
         [6, 5, 7, 8, 8],
         [9, 2, 8, 6, 6]]],


       [[[9, 1, 6, 8, 8],
         [3, 2, 3, 6, 3],
         [6, 5, 7, 0, 8],
         [4, 6, 5, 8, 2]],

        [[3, 9, 7, 5, 3],
         [4, 5, 3, 3, 7],
         [9, 9, 9, 7, 3],
         [2, 3, 9, 7, 7]],

        [[5, 1, 2, 2, 8],
         [1, 5, 8, 4, 0],
         [2, 5, 5, 0, 8],
         [1, 1, 0, 3, 8]]]])

In [64]:
arrandom[:1,:1,:1,:1]

array([[[[2]]]])

## Array Manipulation

In [65]:
array1d


array([1, 2, 3])

In [66]:
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [67]:
array1d+one

array([[2., 3., 4.],
       [2., 3., 4.]])

In [68]:
array1d - one

array([[0., 1., 2.],
       [0., 1., 2.]])

In [69]:
array1d * one

array([[1., 2., 3.],
       [1., 2., 3.]])

In [70]:
array1d % one

array([[0., 0., 0.],
       [0., 0., 0.]])

In [71]:
array2d * array3d

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [72]:
array2d

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
array3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [74]:
m = array3d[:2,:2,:3]

In [75]:
m

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [76]:
 array2d * m

array([[[ 1,  4,  9],
        [16, 25, 36]],

       [[ 1,  4,  9],
        [16, 25, 36]]])

In [77]:
array1d/one

array([[1., 2., 3.],
       [1., 2., 3.]])

In [78]:
array1d//one

array([[1., 2., 3.],
       [1., 2., 3.]])

In [79]:
array1d//array2d

array([[1, 1, 1],
       [0, 0, 0]])

In [80]:
array2d**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [81]:
np.square(array2d)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [82]:
np.add(array1d,array2d)

array([[2, 4, 6],
       [5, 7, 9]])

In [83]:
array3d%2

array([[[1, 0, 1],
        [0, 1, 0],
        [1, 0, 1]],

       [[1, 0, 1],
        [0, 1, 0],
        [1, 0, 1]]], dtype=int32)

## AGGREGATIONS  

In [84]:
# mjy lmbi bt na bta sidha SIDHA YE BTA TOTAL KITNY BNY, LAST SET OF DATA MJY NA DY MJY SUM NIKAL K DEDY


In [85]:
array1d

array([1, 2, 3])

In [86]:
sum(array1d) #lmbi bt na bta bs ye bta total kitna bnta h

## This is python method and also slower

6

In [87]:
np.sum(array1d) ## This is numpy method and also faster

6

In [88]:
#Example
lambi_array = np.random.random(10000)

In [89]:
lambi_array


array([0.05037006, 0.69909807, 0.9923964 , ..., 0.2128151 , 0.08552944,
       0.77890462])

In [90]:
lambi_array.size


10000

In [91]:
lambi_array[:20]

array([0.05037006, 0.69909807, 0.9923964 , 0.26726254, 0.67909062,
       0.86428144, 0.75084425, 0.96448977, 0.55424244, 0.2123905 ,
       0.22244322, 0.21874937, 0.56957353, 0.45210904, 0.97023668,
       0.68054469, 0.08529557, 0.05641833, 0.4878377 , 0.88100456])

In [92]:
np.sum(lambi_array)

5010.21298265909

In [93]:
%timeit sum(lambi_array) #python 
%timeit np.sum(lambi_array) #numpy

2.19 ms ± 387 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
18 µs ± 678 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [94]:
np.max(array1d)

3

In [95]:
np.max(lambi_array)

0.9999709462497284

In [96]:
np.min(lambi_array)

2.0027530115096503e-05

# mean
# variance
# standard deviation

In [97]:
# ap dukandar k ps gye usnny bola ye 100 rupy ka hai apny bola 50 dunga to behas k bd bola ""MEAN"" lelety hn to 75 rupy hogye 

In [98]:
# ek point mean se kitna duur bhatka hua h similarly on average saary points mean value se kitnba duur bhatky hue hn isko ""VARIANCE"" kehty hn

In [99]:
# Variance k square root ko STANDARD DEVIATION kehty hn, square root leny ki kch wajuhat hoti hn jesy ap chahty ho apki value hmesha positive ae jesy TIME

In [100]:
np.mean(array1d)# mean

2.0

In [101]:
np.var(array1d) # variance

0.6666666666666666

In [102]:
np.sqrt(np.var(array1d)) # standard deviation

0.816496580927726

In [103]:
np.std(array1d)  # standard deviation

0.816496580927726

## Matrix Manipulation

In [104]:
# Dot Product vs Element wise manipulation

In [105]:
np.random.seed(seed=0)
matrix_1 = np.random.randint(10, size=(4,3))
matrix_2 = np.random.randint(10, size=(4,3))

In [106]:
matrix_1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6]])

In [107]:
matrix_2

array([[8, 8, 1],
       [6, 7, 7],
       [8, 1, 5],
       [9, 8, 9]])

In [108]:
matrix_1*matrix_2 #lemment Wise Multiplication

array([[40,  0,  3],
       [18, 49, 63],
       [24,  5, 10],
       [36, 56, 54]])

## Dot Product

In [109]:
matrix_1.dot(matrix_2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [ ]:
# column and rows are not equal (4,3) & (4,3) 
#its solution is transpose

In [ ]:
matrix_1.dot(matrix_2.T) #TRANSPOSE swaps rows into column and column into rows

In [ ]:
matrix_1.dot(matrix_2.T).shape

## matrix_2.shape

## Reshape and Transpose

In [ ]:
#TRANSPOSE swwaps rows into column and column into rows

In [ ]:
array2d.shape

In [ ]:
array2d.T.shape

In [ ]:
#We can change dimension of matrix artificially 

In [ ]:
#Reshape
array2d.reshape(2,3,1)

In [ ]:
array2d.reshape(2,3,1).shape

In [ ]:
#EXERCISE
np.random.seed(seed=0)
Item_amount = np.random.randint(20,size=(5,3))
Item_amount

In [ ]:
Item_price = np.array([11,12,9])
Item_price

In [ ]:
Item_Price_dataframe = pd.DataFrame(Item_price.reshape(1,3),
                                    index = ['Item_price'],
                                    columns = ['Item1', 'Item2', 'Item3'])

In [ ]:
Item_Price_dataframe

In [ ]:
Total = Item_amount.dot(Item_price.reshape(4,4))

In [ ]:
Item_Price_dataframe.shape , Item_amount.shape

In [ ]:
Total = Item_Price_dataframe.dot(Item_amount.T)

In [ ]:
Total

In [ ]:
weekly_sales = pd.DataFrame(Item_amount,index=['Mon','Tue','Wed','Thu','Fri'],columns=['Item1', 'Item2', 'Item3'])

In [ ]:
weekly_sales

In [ ]:
weekly_sales['item_price']=Total.T

In [ ]:
weekly_sales

## Comparison Operator

In [ ]:
array1d

In [ ]:
array2d

In [ ]:
array1d>array2d

In [ ]:
a1d = np.array([10,20,1])

In [ ]:
a1d

In [ ]:
a1d>array2d

In [ ]:
array1d == a1d

In [ ]:
array1d == array2d

In [ ]:
array1d != array2d

In [ ]:
array1d < array2d

In [ ]:
array1d <= array2d

In [ ]:
array1d >= array2d

## Sorting Array

In [ ]:
random_matrix = np.random.randint(10, size=(3,5))

In [ ]:
random_matrix

In [ ]:
#I have to arrange array in ascending or descending order or whatever so


In [ ]:
np.sort(random_matrix,axis = 1) #axis = 1 means sorting out rows... its default

In [ ]:
np.sort(random_matrix,axis = 0) #axis = 0 means sorting out column

In [ ]:
np.argsort(random_matrix)

In [ ]:
random_matrix

In [ ]:
np.argmin(random_matrix, axis=1)

In [ ]:
np.min(random_matrix)

In [ ]:
np.argmax(random_matrix, axis=1)

In [ ]:
np.argmax(random_matrix, axis=0)

## Image Data Read

In [ ]:
#from matplotlib.image import imread

In [ ]:
img_data = imread('WhatsApp Image 2023-05-19 at 01.49.08 (3).jpeg')

In [ ]:
img_data #pixel value of this image

In [ ]:
from matplotlib.pyplot as plt

In [ ]:
from matplotlib as mpl

In [ ]:
np.shape(a1d)

In [ ]:
np.a1d_shape()